[package]
name = "btd"
version = "0.1.0"
authors = ["Skye Bleed <monarrk@aaathats3as.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bluetooth-serial-port = "0.5.1"
mio = "0.6"
